#!/bin/bash
if [ -t 1 ];then
echo -e "\e[36m"
sudo apt-get -y update
echo -e "\e[35m"
sudo apt-get -y upgrade
sudo apt-get -y dist-upgrade
echo -e "\e[31m"
sudo apt-get -y autoremove
echo -e "\e[33m"
sudo apt-get -y autoclean
echo -e "\e[0m"
#sudo $(dirname $0)/programming/bash/pepperupdate.sh
else
x-terminal-emulator -x "$0"
fi
