#!/bin/bash
if [ -t 1 ];then
echo -e "\e[36m"
sudo apt-get -y update
echo -e "\e[35m"
sudo apt-get -y upgrade
echo -e "\e[31m"
sudo apt-get -y dist-upgrade
echo -e "\e[33m"
sudo apt-get -y autoremove
sudo apt-get -y autoclean
echo -e "\e[39m"
else
#gksudo -S -m "\"up\" needs root privileges" 'apt-get -y update;apt-get -y upgrade;apt-get -y dist-upgrade;apt-get -y autoremove;apt-get -y autoclean'
gnome-terminal -x "$0"
fi
